version: "3"
services:
  app:
    container_name: astro-sample-app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    restart: always
    command: sh -c 'npm run dev -- --host 0.0.0.0'
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  node_modules:
